title = "Aleksandr Popov"

[author]
name = "Aleksandr Popov"
image = "img/profile.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { email = "mailto:"},
  { github = "https://github.com/budivoy" },
  { linkedin = "https://www.linkedin.com/in/aleksandr-popov-9523aa83" },
  { google = "https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=vaPP57YAAAAJ&sortby=pubdate" }
]
