title = "Aleksandr Popov"

copyright = "The content for this site is [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/), the [code](https://github.com/budivoy/budivoy.github.io) is [Apache 2.0](https://github.com/budivoy/budivoy.github.io/blob/main/LICENSE)"

[author]
name = "Aleksandr Popov"
image = "img/profile.jpg"
headline = "Solving 21st century problems and sometimes working as a 'firefighter'"
bio = "A little bit about me"
links = [
  { email = "mailto:"},
  { github = "https://github.com/budivoy" },
  { linkedin = "https://www.linkedin.com/in/aleksandr-popov-9523aa83" },
  { google = "https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=vaPP57YAAAAJ&sortby=pubdate" }
]
