site_name: Aleksandr Popov - Personal Page
site_url: https://budivoy.github.io
site_author: Aleksandr Popov
site_description: >-
  Personal page

# Repository
repo_name: budivoy/budivoy.github.io
repo_url: https://github.com/budivoy/budivoy.github.io

# Copyright
copyright: Copyright &copy; 2025 Aleksandr Popov

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: rocket-solid
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/budivoy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aleksandr-p-9523aa83/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/xbudivoy
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=vaPP57YAAAAJ&sortby=pubdate

# Extensions
markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md

# Extra Stylesheet
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
  - stylesheets/extra.css
