site_name: Aleksandr Popov
site_url: https://budivoy.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
  font:
    text: Roboto
  icon:
    logo: material/account-circle   
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-night
          name: Switch to light mode

nav:
  - Home: index.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
  - assets/css/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/budivoy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aleksandr-p-9523aa83/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/xbudivoy
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=vaPP57YAAAAJ&sortby=pubdate

copyright: |
  <div style="text-align: center; margin-top: 2rem;">
    The content for this site is <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>, 
    the <a href="https://github.com/budivoy/budivoy.github.io">code</a> is 
    <a href="https://github.com/budivoy/budivoy.github.io/blob/main/LICENSE" target="_blank">Apache 2.0</a>
  </div>

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji

plugins:
  - search
#  - social

repo_url: https://github.com/budivoy/budivoy.github.io
